[project]
authors = ["Katy Scott <k.l.scott16@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "clinical_data_handling"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.6,<4"
jupyterlab = ">=4.2.5,<5"
pandas = ">=2.2.3,<3"
openpyxl = ">=3.1.5,<4"
